import { readFileSync, writeFileSync, mkdirSync } from 'fs'
import { join } from 'path'
import { parseCSV, csvToObjects, truncateClean } from './csv-utils.mjs'

const DATA_DIR = '/projects/sandbox/ui-ux-pro-max-skill/src/ui-ux-pro-max/data'
const OUT_DIR = join(import.meta.dirname, '..', 'src', 'data')

mkdirSync(OUT_DIR, { recursive: true })

function readCSV(filename) {
  const text = readFileSync(join(DATA_DIR, filename), 'utf-8')
  const rows = parseCSV(text)
  return csvToObjects(rows)
}

// Chinese translations for style names
const zhNames = {
  'Minimalism & Swiss Style': '极简主义',
  'Neumorphism': '新拟态',
  'Glassmorphism': '玻璃拟态',
  'Brutalism': '粗野主义',
  '3D & Hyperrealism': '3D超写实',
  'Vibrant & Block-based': '活力色块',
  'Dark Mode (OLED)': '深色模式',
  'Accessible & Ethical': '无障碍设计',
  'Claymorphism': '粘土拟态',
  'Aurora UI': '极光界面',
  'Retro-Futurism': '复古未来',
  'Flat Design': '扁平设计',
  'Skeuomorphism': '拟物化设计',
  'Liquid Glass': '流体玻璃',
  'Motion-Driven': '动效驱动',
  'Micro-interactions': '微交互',
  'Inclusive Design': '包容性设计',
  'Zero Interface': '零界面',
  'Soft UI Evolution': '柔和界面进化',
  'Hero-Centric Design': '主视觉设计',
  'Conversion-Optimized': '转化优化',
  'Storytelling Layout': '故事化布局',
  'Minimal & Direct': '极简直达',
  'Interactive Demo': '互动演示',
  'Product-Led': '产品主导',
  'Social Proof Heavy': '社会认证',
  'Comparison-Focused': '对比聚焦',
  'Waitlist/Pre-launch': '预发布',
  'Long-form Sales': '长文案销售',
  'Card-based Commerce': '卡片电商',
  'Immersive Product': '沉浸式产品',
  'Speed Commerce': '极速电商',
  'Luxury E-commerce': '奢侈品电商',
  'Marketplace Multi-vendor': '多商户市集',
  'Subscription Commerce': '订阅制电商',
  'Social Commerce': '社交电商',
  'Data-Dense Dashboard': '数据密集仪表盘',
  'Executive Dashboard': '管理层仪表盘',
  'Real-Time Monitoring': '实时监控',
  'Analytics & Insights': '分析洞察',
  'Creative Dashboard': '创意仪表盘',
  'Mobile-First Minimal': '移动优先极简',
  'Gesture-Heavy Mobile': '手势驱动移动端',
  'Bottom-Nav Mobile': '底部导航移动端',
  'Card-Stack Mobile': '卡片堆叠移动端',
  'Super App Mobile': '超级应用移动端',
  'Long-form Content': '长文内容',
  'Magazine Editorial': '杂志编辑',
  'Documentation/Wiki': '文档知识库',
  'Blog/Personal': '博客个人',
  'News/Media Feed': '新闻媒体流',
  'Social Feed': '社交动态流',
  'Community Platform': '社区平台',
  'Messaging/Chat': '即时通讯',
  'Creator Platform': '创作者平台',
  'Enterprise SaaS': '企业级SaaS',
  'Admin Panel': '管理后台',
  'CRM Interface': 'CRM界面',
  'Internal Tools': '内部工具',
  'Design Tool UI': '设计工具界面',
  'Code Editor UI': '代码编辑器界面',
  'Music/Audio UI': '音频界面',
  'Video Platform': '视频平台',
  'AI/ML Interface': 'AI智能界面',
  'Gamified UI': '游戏化界面',
  'Organic & Natural': '有机自然风',
  'Cyberpunk': '赛博朋克',
}

function generatePromptZh(style) {
  const name = zhNames[style['Style Category']] || style['Style Category']
  const effects = style['Effects & Animation'] || '视觉效果'
  const colors = style['Primary Colors'] || '品牌色'
  const bestFor = style['Best For'] || '通用场景'
  const css = style['CSS/Technical Keywords'] || 'CSS3'
  
  return `请设计一个${name}界面。使用：${truncateClean(effects, 60)}。配色：${truncateClean(colors, 50)}。适用于：${truncateClean(bestFor, 50)}。技术要点：${truncateClean(css, 60)}。`
}

// Process styles
const stylesRaw = readCSV('styles.csv')
const styles = stylesRaw.map((s, i) => ({
  id: parseInt(s['No']) || i + 1,
  nameEn: s['Style Category'] || '',
  nameZh: zhNames[s['Style Category']] || s['Style Category'],
  type: s['Type'] || 'General',
  keywords: (s['Keywords'] || '').split(',').map(k => k.trim()).filter(Boolean),
  primaryColors: s['Primary Colors'] || '',
  secondaryColors: s['Secondary Colors'] || '',
  effects: s['Effects & Animation'] || '',
  bestFor: s['Best For'] || '',
  doNotUseFor: s['Do Not Use For'] || '',
  lightMode: s['Light Mode ✓'] || '',
  darkMode: s['Dark Mode ✓'] || '',
  performance: s['Performance'] || '',
  accessibility: s['Accessibility'] || '',
  mobileFriendly: s['Mobile-Friendly'] || '',
  conversionFocused: s['Conversion-Focused'] || '',
  frameworkCompat: s['Framework Compatibility'] || '',
  era: s['Era/Origin'] || '',
  complexity: s['Complexity'] || '',
  promptEn: s['AI Prompt Keywords'] || '',
  promptZh: generatePromptZh(s),
  cssKeywords: s['CSS/Technical Keywords'] || '',
  implementationChecklist: (s['Implementation Checklist'] || '').split('☐').map(c => c.trim()).filter(Boolean),
  designVariables: s['Design System Variables'] || '',
}))

// Process products
const productsRaw = readCSV('products.csv')
const productZhNames = {
  'SaaS (General)': '通用SaaS',
  'Micro SaaS': '微型SaaS',
  'E-commerce (General)': '通用电商',
  'E-commerce': '电商平台',
  'E-commerce Luxury': '奢侈品电商',
  'FinTech': '金融科技',
  'Fintech/Crypto': '金融科技/加密货币',
  'EdTech': '教育科技',
  'HealthTech': '健康科技',
  'AI/ML Platform': 'AI/ML平台',
  'AI/Chatbot Platform': 'AI聊天机器人平台',
  'Social Media': '社交媒体',
  'Social Media App': '社交媒体应用',
  'Marketplace': '交易市场',
  'Marketplace (P2P)': 'P2P交易市场',
  'Gaming': '游戏',
  'Food & Delivery': '餐饮外卖',
  'Food Delivery / On-Demand': '外卖/即时配送',
  'Travel & Booking': '旅行预订',
  'Travel/Tourism Agency': '旅游机构',
  'Real Estate': '房地产',
  'Real Estate/Property': '房地产/物业',
  'Fitness & Wellness': '健身养生',
  'Fitness/Gym App': '健身应用',
  'News & Media': '新闻媒体',
  'News/Media Platform': '新闻媒体平台',
  'B2B Service': 'B2B服务',
  'Financial Dashboard': '金融仪表盘',
  'Analytics Dashboard': '数据分析仪表盘',
  'Healthcare App': '医疗健康应用',
  'Educational App': '教育应用',
  'Creative Agency': '创意机构',
  'Portfolio/Personal': '个人作品集',
  'Government/Public Service': '政府/公共服务',
  'Productivity Tool': '效率工具',
  'Design System/Component Library': '设计系统/组件库',
  'NFT/Web3 Platform': 'NFT/Web3平台',
  'Creator Economy Platform': '创作者经济平台',
  'Remote Work/Collaboration Tool': '远程协作工具',
  'Mental Health App': '心理健康应用',
  'Pet Tech App': '宠物科技应用',
  'Smart Home/IoT Dashboard': '智能家居/IoT面板',
  'EV/Charging Ecosystem': '电动车/充电生态',
  'Subscription Box Service': '订阅盒子服务',
  'Podcast Platform': '播客平台',
  'Dating App': '社交约会应用',
  'Micro-Credentials/Badges Platform': '微证书/徽章平台',
  'Knowledge Base/Documentation': '知识库/文档',
  'Hyperlocal Services': '本地化服务',
  'Beauty/Spa/Wellness Service': '美容/水疗服务',
  'Luxury/Premium Brand': '奢侈品/高端品牌',
  'Restaurant/Food Service': '餐饮服务',
  'Hotel/Hospitality': '酒店/住宿服务',
  'Wedding/Event Planning': '婚礼/活动策划',
  'Legal Services': '法律服务',
  'Insurance Platform': '保险平台',
  'Banking/Traditional Finance': '银行/传统金融',
  'Online Course/E-learning': '在线课程/学习',
  'Non-profit/Charity': '非营利/公益',
  'Music Streaming': '音乐流媒体',
  'Video Streaming/OTT': '视频流媒体/OTT',
  'Job Board/Recruitment': '招聘平台',
  'Logistics/Delivery': '物流/配送',
  'Agriculture/Farm Tech': '农业科技',
  'Construction/Architecture': '建筑/工程',
  'Automotive/Car Dealership': '汽车/经销商',
  'Photography Studio': '摄影工作室',
  'Coworking Space': '联合办公空间',
  'Home Services (Plumber/Electrician)': '家庭维修服务',
  'Childcare/Daycare': '托儿/幼托',
  'Senior Care/Elderly': '养老/老年护理',
  'Medical Clinic': '医疗诊所',
  'Pharmacy/Drug Store': '药店/药房',
  'Dental Practice': '牙科诊所',
  'Veterinary Clinic': '宠物医院',
  'Florist/Plant Shop': '花店/植物商店',
  'Bakery/Cafe': '烘焙/咖啡店',
  'Brewery/Winery': '酿酒厂/酒庄',
  'Sports Team/Club': '体育俱乐部',
  'Church/Religious Organization': '宗教组织',
  'Museum/Gallery': '博物馆/画廊',
  'Theater/Cinema': '剧院/影院',
  'Marketing Agency': '营销机构',
  'Freelancer Platform': '自由职业者平台',
  'Event Management': '活动管理',
  'Magazine/Blog': '杂志/博客',
  'Newsletter Platform': '新闻通讯平台',
  'Membership/Community': '会员/社区',
  'Digital Products/Downloads': '数字产品/下载',
  'Coding Bootcamp': '编程训练营',
  'Language Learning App': '语言学习应用',
  'Habit Tracker': '习惯追踪器',
  'Meditation & Mindfulness': '冥想正念',
  'Sleep Tracker': '睡眠追踪器',
  'Recipe & Cooking App': '食谱/烹饪应用',
  'Grocery & Shopping List': '购物清单应用',
  'Weather App': '天气应用',
  'Calendar & Scheduling App': '日历/日程应用',
  'Notes & Writing App': '笔记/写作应用',
  'Personal Finance Tracker': '个人理财追踪',
  'Password Manager': '密码管理器',
  'VPN & Privacy Tool': 'VPN/隐私工具',
  'Cybersecurity Platform': '网络安全平台',
  'Developer Tool / IDE': '开发者工具/IDE',
  'Inventory & Stock Management': '库存管理',
  'Invoice & Billing Tool': '发票/账单工具',
  'CRM & Client Management': 'CRM/客户管理',
  'Generative Art Platform': '生成艺术平台',
  'AI Photo & Avatar Generator': 'AI照片/头像生成',
  'Space Tech / Aerospace': '航天科技',
  'Biotech / Life Sciences': '生物科技/生命科学',
  'Quantum Computing Interface': '量子计算界面',
  'Autonomous Drone Fleet Manager': '无人机管理平台',
  'Sustainable Energy / Climate Tech': '可持续能源/气候科技',
  'Spatial Computing OS / App': '空间计算应用',
  'Ride Hailing / Transportation': '网约车/出行',
  'Parking Finder': '停车位查找',
  'Public Transit Guide': '公交导航',
  'Road Trip Planner': '自驾旅行规划',
  'Running & Cycling GPS': '跑步/骑行GPS',
  'Yoga & Stretching Guide': '瑜伽/拉伸指导',
  'Calorie & Nutrition Counter': '卡路里/营养计算',
  'Fasting & Intermittent Timer': '间歇性断食计时',
  'Water & Hydration Reminder': '喝水提醒',
  'Medication & Pill Reminder': '服药提醒',
  'Period & Cycle Tracker': '经期追踪',
  'Mood Tracker': '情绪追踪',
  'Diary & Journal App': '日记应用',
  'Biohacking / Longevity App': '生物黑客/长寿应用',
  'Kids Learning (ABC & Math)': '儿童学习应用',
  'Flashcard & Study Tool': '闪卡/学习工具',
  'Study Together / Virtual Coworking': '线上自习室',
  'Coding Challenge & Practice': '编程挑战/练习',
  'Music Instrument Learning': '乐器学习',
  'Book & Reading Tracker': '阅读追踪器',
  'Bookmark & Read-Later': '收藏/稍后阅读',
  'Chat & Messaging App': '聊天/通讯应用',
  'Anonymous Community / Confession': '匿名社区/树洞',
  'Couple & Relationship App': '情侣/关系应用',
  'Family Calendar & Chores': '家庭日历/家务',
  'Parenting & Baby Tracker': '育儿/宝宝追踪',
  'Plant Care Tracker': '植物养护追踪',
  'Home Decoration & Interior Design': '家装/室内设计',
  'Wardrobe & Outfit Planner': '衣橱/穿搭规划',
  'Gift & Wishlist': '礼物/愿望清单',
  'Local Events & Discovery': '本地活动/发现',
  'Booking & Appointment App': '预约应用',
  'Expense Splitter / Bill Split': 'AA/分账应用',
  'Link-in-Bio Page Builder': '个人链接页构建',
  'Photo Editor & Filters': '照片编辑/滤镜',
  'Short Video Editor': '短视频编辑',
  'Drawing & Sketching Canvas': '绘画/素描画布',
  'Meme & Sticker Maker': '表情包/贴纸制作',
  'Music Creation & Beat Maker': '音乐创作/节拍器',
  'Voice Recorder & Memo': '录音/语音备忘',
  'Wallpaper & Theme App': '壁纸/主题应用',
  'Timer & Pomodoro': '计时器/番茄钟',
  'Alarm & World Clock': '闹钟/世界时钟',
  'Calculator & Unit Converter': '计算器/单位转换',
  'Scanner & Document Manager': '扫描/文档管理',
  'File Manager & Transfer': '文件管理/传输',
  'Translator App': '翻译应用',
  'Email Client': '邮件客户端',
  'White Noise & Ambient Sound': '白噪音/环境音',
  'Casual Puzzle Game': '休闲益智游戏',
  'Trivia & Quiz Game': '问答/竞猜游戏',
  'Word & Crossword Game': '文字/填字游戏',
  'Card & Board Game': '纸牌/棋盘游戏',
  'Idle & Clicker Game': '放置/点击游戏',
  'Arcade & Retro Game': '街机/复古游戏',
  'Architecture / Interior': '建筑/室内设计',
  'Emergency SOS & Safety': '紧急求助/安全',
  'Airline': '航空公司',
}

const products = productsRaw.map((p, i) => ({
  id: parseInt(p['No']) || i + 1,
  name: p['Product Type'] || '',
  nameZh: productZhNames[p['Product Type']] || p['Product Type'],
  keywords: (p['Keywords'] || '').split(',').map(k => k.trim()).filter(Boolean),
  primaryStyle: p['Primary Style Recommendation'] || '',
  secondaryStyles: p['Secondary Styles'] || '',
  landingPattern: p['Landing Page Pattern'] || '',
  dashboardStyle: p['Dashboard Style (if applicable)'] || '',
  colorFocus: p['Color Palette Focus'] || '',
  considerations: p['Key Considerations'] || '',
}))

// Write output files
function writeTS(filename, varName, data, typeName) {
  const content = `import type { ${typeName} } from './types'\n\nexport const ${varName}: ${typeName}[] = ${JSON.stringify(data, null, 2)}\n`
  writeFileSync(join(OUT_DIR, filename), content, 'utf-8')
}

writeTS('styles.ts', 'styles', styles, 'UIStyle')
writeTS('products.ts', 'products', products, 'ProductType')

// Write index
const indexContent = `export { styles } from './styles'
export { products } from './products'
export type { UIStyle, ProductType, ColorPalette, FontPairing, StyleCategory } from './types'
`
writeFileSync(join(OUT_DIR, 'index.ts'), indexContent, 'utf-8')

console.log(`Generated data files:`)
console.log(`  - styles.ts: ${styles.length} styles`)
console.log(`  - products.ts: ${products.length} products`)
